/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    'index',
    'getting-started',
    {
      type: 'category',
      label: 'Organization',
      items: [
        'organization/overview',
        'organization/people',
        {
          type: 'category',
          label: 'Teams',
          items: [
            'organization/teams/data/data-team',
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'How To',
      items: [
        'how-to/aws-sso-login'
      ],
    },
  ],
};

module.exports = sidebars;
