/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  default: [
    'index',
    {
      type: 'category',
      label: 'Organization',
      items: [
        'organization/overview',
        'organization/roles-and-missions',
        'organization/career-paths',
        'organization/tech-radar',
        'organization/people',
        {
          type: 'category',
          label: 'Teams',
          items: [
            'organization/teams/data-team',
            'organization/teams/platform-engineering-team'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Style Guide',
      items: [
        {
          type: 'category',
          label: 'Coding',
          items: [
            'style-guide/coding/ts-style-guide',
            'style-guide/coding/py-style-guide',
            'style-guide/coding/documentation-style-guide',
          ]
        },
        {
          type: 'category',
          label: 'Cloud',
          items: [
            'style-guide/cloud/aws-style-guide',
            'style-guide/cloud/gcp-style-guide',
          ]
        },
        {
          type: 'category',
          label: 'GitHub',
          items: [
            'style-guide/github/pull-request',
            'style-guide/github/issues',
            'style-guide/github/workflows',
          ]
        }
      ]
    },
  ],
};

module.exports = sidebars;
