/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  default: [
    'index',
    {
      type: 'category',
      label: '🚀 Organization',
      items: [
        'organization/overview',
        'organization/roles-and-missions',
        'organization/career-paths',
        'organization/tech-radar',
        'organization/people'
      ],
      link: {
        type: 'generated-index',
        title: 'Organization',
        slug: '/organization',
        keywords: ['guides'],
      },
    },
    {
      type: 'category',
      label: '⭐ Teams',
      items: [
        'teams/data-team',
        'teams/platform-engineering-team'
      ],
      link: {
        type: 'generated-index',
        title: 'Teams',
        slug: '/teams',
        keywords: ['guides'],
      },
    }
  ],
};

module.exports = sidebars;
